import '../../Product.dart';

final products = [
  Product(
    imagePath: "Assets/image 5.png",
    title: "زيت ليكو مولي",
    subtitle: "تويوتا كورولا 45433689 زيت محرك",
    price: "120.00",
    oldPrice: "150.00",
    discount: "20%",
    category: "#زيوت",
    sellerName: "متجر السيارات",
    rating: 4.2,
    ratersCount: 120,
    comments: ["منتج ممتاز!", "يعمل بشكل جيد مع سيارتي."],
  ),
  Product(
    imagePath: "Assets/image 5.png",
    title: "فلتر هواء",
    subtitle: "فلتر محرك هيونداي",
    price: "45.00",
    oldPrice: "60.00",
    discount: "25%",
    category: "#فلاتر",
    sellerName: "متجر القطع",
    rating: 4.5,
    ratersCount: 85,
    comments: ["جودة عالية", "سهل التركيب"],
  ),
  Product(
    imagePath: "Assets/image 5.png",
    title: "بواجي NGK",
    subtitle: "شمعات إشعال أصلي",
    price: "80.00",
    oldPrice: "100.00",
    discount: "20%",
    category: "#بواجي",
    sellerName: "متجر NGK",
    rating: 4.2,
    ratersCount: 95,
    comments: ["أداء رائع", "توصيل سريع"],
  ),
  Product(
    imagePath: "Assets/image 5.png",
    title: "بطارية فارتا",
    subtitle: "بطارية 70 أمبير",
    price: "300.00",
    oldPrice: "400.00",
    discount: "25%",
    category: "#بطاريات",
    sellerName: "متجر البطاريات",
    rating: 4.8,
    ratersCount: 200,
    comments: ["عمر طويل", "ممتازة"],
  ),
];
